config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  mount Rswag::Ui::Engine => '/api-docs'
  mount Rswag::Api::Engine => '/api-docs'
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations',
    passwords: 'users/passwords'
  }

  namespace :api do
    namespace :v1 do
      post 'login', to: 'login#auth'
      resources :users, only: [:index, :show] do
        resources :posts, only: [:index] do
          resources :comments, only: [:index, :create]
        end
      end
    end
  end

  
  root 'users#index'
  get '/users', to: 'users#index', as: 'users'

  get '/users/:id', to: 'users#show', as: 'user'

  get '/users/:user_id/posts', to: 'posts#index', as: 'user_posts'
  get '/users/:user_id/posts/new', to: 'posts#new', as: 'new_user_post'
  post '/users/:user_id/posts', to: 'posts#create'
  get '/users/:user_id/posts/:id', to: 'posts#show', as: 'user_post'
  delete '/users/:user_id/posts/:id', to: 'posts#destroy', as: 'destroy_user_post'
  get '/users/:user_id/posts/:post_id/comments', to: 'comments#index', as: 'comments'
  get '/users/:user_id/posts/:post_id/new', to: 'comments#new', as: 'new_comment'
  post '/users/:user_id/posts/:post_id', to: 'comments#create', as: 'create_comment'
  delete '/users/:user_id/posts/:post_id/:id', to: 'comments#destroy', as: 'destroy_comment'

  post '/users/:user_id/posts/:post_id/likes', to: 'likes#create', as: 'create_like'
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  #  :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :confirmable, :validatable
  has_many :posts, foreign_key: :author_id
  has_many :comments, foreign_key: :author_id
  has_many :likes, foreign_key: :author_id

  # Validations
  validates :Name, presence: true, length: { minimum: 3, maximum: 20 }
  validates :PostCounter, presence: true, numericality: { only_integer: true, greater_than_or_equal_to: 0 }

  # A method that returns the 3 most recent posts for a given user.
  def return_three_most_recent_posts
    posts.order(created_at: :desc).limit(3)
  end

  def update_posts_counter
    update(PostCounter: posts.count)
  end
end

app/controllers/api/v1/users_controller.rb
class Api::V1::UsersController < ApiController
  def index
    @users = User.all
    render json: @users
  end

  def show
    render json: User.find(params[:id])
  end
end

app/controllers/users/passwords_controller.rb
module Users
  class PasswordsController < Devise::PasswordsController
  end
end

app/controllers/users/registrations_controller.rb
module Users
  class RegistrationsController < Devise::RegistrationsController
  end
end

app/controllers/users/sessions_controller.rb
module Users
  class SessionsController < Devise::SessionsController
    def after_sign_in_path_for(_resource)
      root_path
    end
    # ...
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def show
    if params[:id] == 'sign_out'
      sign_out(current_user)
    else
      @user = User.find_by_id(params[:id])
      render :invalid_user if @user.nil?
      @recent_posts = @user.return_three_most_recent_posts
    end
  end

  def invalid_user
    render :invalid_user
  end
end

app/views/users/index.html.erb
<h1 class ="usersTitle">List of all users</h1>
<%= render 'shared/login_as' %>
<div class= "allUsers">
  <% @users.each do |user| %>
    <%= link_to render(partial: 'shared/user_info', locals: { user: user }), user_path(user), class: "container" %>
  <% end %>
</div>

app/views/users/invalid_user.html.erb
<h1 class ="usersTitle"> You are trying to access an invalid user, please go to a valid profile </h1>
<%= button_to 'go back to home', root_path, method: :get, class: 'btnPosts' %>

app/views/users/show.html.erb
<h1 class ="usersTitle"> users details</h1>
<%= render 'shared/login_as' %>
<div class= "userProfile">
<% if @user %>
  <%= render partial: "shared/user_info", locals: { user: @user } %>
  <div class = "bioContainer" >
    <h2> Bio </h2>
    <p class = "bio">
      <%= @user.Bio %>
    </p>
  </div>
  <% @recent_posts.each_with_index do |post, index| %>
    <div class = "post post-identifier">
      <p>
        Post #<%= index + 1 %>
      </p>
      <p class = "postTitle">
    <%= link_to post.Title, user_post_path(@user.id, post.id) %>
      </p>
      <p class = "postContent">
        <%= post.Text %>
      </p>
      <div class = "counters">
        <span> 
          Comments: <%= post.CommentsCounter == nil ?  0 : post.CommentsCounter  %>
        </span>
        <span> 
          Likes: <%= post.LikesCounter == nil ? 0 : post.LikesCounter  %>
        </span>
      </div>
  </div>
  <% end %>
  <%= button_to 'See all posts', user_posts_path(@user.id), method: :get, class: 'btnPosts' %>
  <% else %>
    No user info
  <% end %>
</div>