config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  mount Rswag::Ui::Engine => '/api-docs'
  mount Rswag::Api::Engine => '/api-docs'
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations',
    passwords: 'users/passwords'
  }

  namespace :api do
    namespace :v1 do
      post 'login', to: 'login#auth'
      resources :users, only: [:index, :show] do
        resources :posts, only: [:index] do
          resources :comments, only: [:index, :create]
        end
      end
    end
  end

  
  root 'users#index'
  get '/users', to: 'users#index', as: 'users'

  get '/users/:id', to: 'users#show', as: 'user'

  get '/users/:user_id/posts', to: 'posts#index', as: 'user_posts'
  get '/users/:user_id/posts/new', to: 'posts#new', as: 'new_user_post'
  post '/users/:user_id/posts', to: 'posts#create'
  get '/users/:user_id/posts/:id', to: 'posts#show', as: 'user_post'
  delete '/users/:user_id/posts/:id', to: 'posts#destroy', as: 'destroy_user_post'
  get '/users/:user_id/posts/:post_id/comments', to: 'comments#index', as: 'comments'
  get '/users/:user_id/posts/:post_id/new', to: 'comments#new', as: 'new_comment'
  post '/users/:user_id/posts/:post_id', to: 'comments#create', as: 'create_comment'
  delete '/users/:user_id/posts/:post_id/:id', to: 'comments#destroy', as: 'destroy_comment'

  post '/users/:user_id/posts/:post_id/likes', to: 'likes#create', as: 'create_like'
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :author, class_name: :User
  has_many :comments
  has_many :likes

  # Validations
  validates :Title, presence: true, length: { minimum: 3, maximum: 250 }
  validates :Text, presence: true, length: { minimum: 1, maximum: 3000 }
  validates :CommentsCounter, presence: true, numericality: { only_integer: true, greater_than_or_equal_to: 0 }
  validates :LikesCounter, presence: true, numericality: { only_integer: true, greater_than_or_equal_to: 0 }

  # A method that updates the posts counter for a user.
  def update_posts_counter
    author.update(PostCounter: author.posts.count)
  end

  # A method which returns the 5 most recent comments for a given post.
  def return_five_most_recent_comments
    comments.order(created_at: :desc).limit(5)
  end

  def update_comments_counter
    update(CommentsCounter: comments.count)
  end
end

app/controllers/api/v1/posts_controller.rb
class Api::V1::PostsController < ApiController
  def index
    @user = User.includes(:posts).find(params[:user_id])
    render json: @user.posts
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  load_and_authorize_resource
  include PostsHelper

  def index
    @user = User.includes(posts: { comments: :author }).find_by(id: params[:user_id])
    redirect_to '/users/invalid_user' if @user.nil?
    @posts = @user.posts

    respond_to do |format|
      format.html
      format.json { render json: @posts }
    end
  end

  def new
    @user = User.find_by_id(params[:user_id])
  end

  def create
    @user = User.find_by_id(params[:user_id])
    @post = @user.posts.new(post_params)
    @post.CommentsCounter = 0
    @post.LikesCounter = 0

    if @post.save
      @post.update_posts_counter
      redirect_to user_posts_path(user_id: @user.id)
    else
      render :new
    end
  end

  def show
    @user = User.find_by_id(params[:user_id])
    @post = @user.posts.includes(:comments, :author).find_by_id(params[:id])
    redirect_to '/users/invalid_user' if @post.nil? || @user.nil?
  end

  def destroy
    @user = User.find_by_id(params[:user_id])
    @post = Post.find_by_id(params[:id])

    if can?(:destroy, @post) # Check if the current user is authorized to delete the post
      @post.likes.destroy_all
      @post.comments.destroy_all
      @post.destroy
      @user.update_posts_counter
      redirect_to user_posts_path(user_id: @user.id), notice: 'Post was successfully deleted.'
    else
      redirect_to user_post_path(user_id: @user.id, id: @post.id), alert: 'You are not authorized to delete this post.'
    end
  end

  private

  def post_params
    params.require(:post).permit(:Title, :Text)
  end
end

app/helpers/posts_helper.rb
module PostsHelper
  def user?(user)
    @current_user == user
  end
end

app/views/posts/index.html.erb
<h1 class ="usersTitle" > All the post of the user </h1>
<%= render 'shared/login_as' %>
<div class= "userProfile">
  <%= render partial: "shared/user_info", locals: { user: @user } %>
    <div class = "postsContainer">
    <% @posts.each do |post|%>
      <div class = "potsAndComments">
        <div class= "post">
          <h2>
            <%= link_to post.Title, user_post_path(@user.id, post.id)  %>
          </h2>
          <p>
          <%= post.Text.length > 100 ? post.Text[0..100].concat('...') : post.Text  %>
          </p>
          <div class = "counters">
            <span> 
              Comments: <%= post.CommentsCounter == nil ?  0 : post.CommentsCounter  %>
            </span>
            ,
            <span> 
              Likes: <%= post.LikesCounter == nil ? 0 : post.LikesCounter  %>
            </span>
          </div>
        </div>
        <div class= "postComments">
        <% if post.comments.any? %>
          <% post.return_five_most_recent_comments.each do |comment| %>
            <p>
              <%= comment.author.Name %>
              :
              <%= comment.Text %>
            </p>
          <% end %>
          <% else %>
            <p>
              No comments yet
            </p>
        <% end %>
        </div>
      </div>
    <% end %>
    </div>
    <% if user?(@user)%>
      <%= button_to 'New post', new_user_post_path, method: :get, class: 'btnPosts'%>
    <% end %>
    <%= button_to 'Back to all the users', root_path, method: :get, class: 'btnPosts'%>
</div>

app/views/posts/new.html.erb
<h1 class ="usersTitle"> New post </h1>
<%= form_with model: Post, url: user_posts_path, class: 'form', method: :post do |form| %>
  <div class= "formDiv">
    <%= form.label :Title %>
    <%= form.text_field :Title %>
  </div>

  <div class= "formDiv">
    <%= form.label :Text %>
    <%= form.text_area :Text %>
  </div>

  <div class = "formDiv">
    <%= form.submit 'Create Post', class: 'btnPosts' %>
  </div>
<% end %>

app/views/posts/show.html.erb
<h1 class ="usersTitle"> All the details of a post from specified user </h1>
<%= render 'shared/login_as' %>
<div class = "userProfile postDetails" >
  <div class = "postInformation">
    <h2> <%= @post.Title %> by <%= @user.Name %> </h2>
      <div class = "counters">
        <span> 
          Comments: <%= @post.CommentsCounter == nil ?  0 : @post.CommentsCounter  %>
        </span>
        ,
        <span> 
          Likes: <%= @post.LikesCounter == nil ? 0 : @post.LikesCounter  %>
        </span>
      </div>
      <p>
        <%= @post.Text %>
      </p>
  </div>
  <div class= "postComments">
    <% if @post.comments.any? %>
      <% @post.comments.each do |comment| %>
      <div class= "commentContainer">
          <p>
            <%= comment.author.Name %>
            :
            <%= comment.Text %>
          </p>
          <% if can?(:destroy, comment)%>
            <%= button_to 'Delete comment', destroy_comment_path(user_id: @user.id, post_id: @post.id, id: comment.id), method: :delete, data: { confirm: 'Are you sure?' }, class: 'btnPosts btnComment deleteComment'  %>
          <% end %>
      </div>
        <% end %>
        <% else %>
          <p>
            No comments yet
          </p>
        <% end %>
  </div>
  <% if can?(:destroy, @post) %>
    <%= button_to 'Delete Post', destroy_user_post_path(post_id: @post.id), method: :delete, data: { confirm: 'Are you sure?' }, class: 'btnPosts btnComment'  %>
  <% end %>
  <%= button_to 'Create a comment', new_comment_path(user_id: @user.id, post_id: @post.id), method: :get, class: 'btnPosts btnComment'  %>
  <%= button_to 'Give like', create_like_path(user_id: @user.id, post_id: @post.id), method: :post, class: 'btnPosts btnComment' %>
  <%= button_to 'Back to all the posts', user_posts_path, method: :get, class: 'btnPosts btnMargin'%>
</div>